apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vote-aggregator
  namespace: "{{ env['GCP_PROJECT_ID'] }}"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: redis-vpc-con
    spec:
      containers:      
      - image: "{{ env['GCP_REGION'] }}-docker.pkg.dev/{{ env['GCP_PROJECT_ID'] }}/blockydevs/vote-aggregator:latest"
        name: vote-aggregator
        ports:
        - containerPort: 8080
        env:
        - name: ESPv2_ARGS
          value: "{{ env['ESPv2_ARGS'] }}"
        - name: REDIS_HOST
          value: "{{ env['REDIS_HOST'] }}"
        - name: REDIS_PORT
          value: "{{ env['REDIS_PORT'] }}"
        - name: REDIS_CURRENT_LOCATION_ID
          value: "{{ env['REDIS_CURRENT_LOCATION_ID'] }}"
        - name: NODE_PORT
          value: "{{ env['NODE_PORT'] }}"
        - name: HUB_RPC_URL
          value: "{{ env['HUB_RPC_URL'] }}"
        - name: HUB_ADDRESS
          value: "{{ env['HUB_ADDRESS'] }}"
        - name: HUB_CHAIN_NAME
          value: "{{ env['HUB_CHAIN_NAME'] }}"
        - name: REDIS_EXPIRATION_TIME_IN_SEC
          value: "{{ env['REDIS_EXPIRATION_TIME_IN_SEC'] }}"
{%- for item in NETWORK_PARAMS %}
        - name: NETWORK_{{ item.NETWORK_DISPLAY_NAME | upper }}_CHAIN_ID
          value: "{{ item.NETWORK_CHAIN_ID }}"
        - name: NETWORK_{{ item.NETWORK_DISPLAY_NAME | upper }}_DISPLAY_NAME
          value: "{{ item.NETWORK_DISPLAY_NAME }}"
        - name: NETWORK_{{ item.NETWORK_DISPLAY_NAME | upper }}_RPC_URL
          value: "{{ item.NETWORK_RPC_URL }}"
        - name: NETWORK_{{ item.NETWORK_DISPLAY_NAME | upper }}_SPOKE_ADDRESS
          value: "{{ item.NETWORK_SPOKE_ADDRESS }}"
{%- endfor %}